version: "3"
services:
  web:
    container_name: "goapp"
    image: golang:1.16
    volumes:
      - ./:/code
    tty: true
    stdin_open: true
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 9000:9000
  proxy:
    build:
        context: .
        dockerfile: nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - web

    
 